### PR TITLE
Update zh_cn for 1.19

### PR DESCRIPTION
**Pull request by ChuijkYahus**
flatten.json5 and unflattened version would both be updated.

### CODE REVIEW

**Comment by object-Object** [comment]
okay these changes need to go into `1.19`, but I guess it'll take a bit of Git surgery to do that

**Comment by object-Object** [comment]
actually i have no idea where these need to go. I guess #512 is the 1.20 changes. @ChuijkYahus when you have a moment, could you check and see if the translations on the `1.19` branch are up to date? https://github.com/gamma-delta/HexMod/tree/1.19/Common/src/main/resources/assets/hexcasting/lang

**Comment by ChuijkYahus** [comment]
Sorry for stale PR changes, the file do need to go to 1.19.
Done checking, fixed differences I could find.

**Comment by object-Object** [comment]
thank you for the quick response! I just moved these changes to #535 to make it easier to merge into the 1.19 branch.

**Pull request closed without merging**
