### PR TITLE
Simplified Chinese trsl

### PR DESCRIPTION
**Pull request by ChuijkYahus**
Co-Authored-By: dovisutu <https://github.com/dovisutu>

This was done on en_us in main branch.
_Hope that there aren't too many changes to lang files in later updates._

### CODE REVIEW

**Comment by ChuijkYahus** [comment]
Gonna update to the version in main branch very soon

**Comment by gamma-delta** [comment]
Oh my god I completely missed this. Thank you so much.

I'm hesitant to merge it right now just because it's been so long since you pushed it, but if you give it another once-over I'll merge it.

对不起！谢谢你！

**Comment by ChuijkYahus** [comment]
Done skimming for another time

Though I think L273 should be Chronicler's Gambit or should be `read/entity`

**Comment by ChuijkYahus** [comment]
Also if you need a version for current 1.18.2 I'll push it too

**Comment by gamma-delta** [comment]
Your choice! (I think you'll have to do it as a new PR?)

**Pull request merged**
